version: "3.7"
services:
  backend:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      - PORT=5000
      - DATABASE_URL=sqlite:///data.db
      - JWT_SECRET_KEY=cc878440-91e0-4a07-b893-ef83b97a3256
      - TODOS_PROVIDER=https://jsonplaceholder.typicode.com/todos
    command: bash start.sh
