version: "3.7"
services:
  backend:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    environment:
      - PORT=5000
    command: flask run --host 0.0.0.0 --debug
